version: '2.1'
orbs:
  docker: circleci/docker@2.0.2
workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          image: favish/drupal-cron
          update-description: true
          tag: $CIRCLE_TAG